default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sloboda_development
  username: postgres
  password: 3441

test:
  <<: *default
  database: sloboda_test
  username: postgres
  password: 3441

production:
  <<: *default
  database: dah7lf0atuirrh
  username: vcqozrkwslgmto
  password: 89bf25005009e3c61c7f0ce84cdd524b5fbca3196fd884a4a7b6b3a34af19a13